ShoppinngCart/src/main/java/com/niit/shoppingcart/model/Product.java
package com.niit.shoppingcart.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "Product")
@Component
public class Product {

	@javax.persistence.Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Id")
	private int Id;
	private String Name;
	private String Description;
	private String primarymaterial;
	private String style;
	private String warranty;
	private String capacity;
	@OneToOne(cascade=CascadeType.PERSIST)
	@JoinColumn(name="suppiler")
	private Suppiler suppiler;
	private int quantity;
	private double Price;
	@Column(name = "image", columnDefinition = "varchar(255)")
	@Size(min = 3, message = "Please Select the Image")
	private String image;
	
	public Product(int Id,String Name,String Description,String primarymaterial,String style,String warranty,String capacity,Suppiler supplier,int supplierid,String suppliername,int quantity,double Price,String image,MultipartFile img) {
	this.Id=Id;
	this.Name = Name;
	this.Description = Description;
	this.primarymaterial = primarymaterial;
	this.style = style;	
	this.warranty = warranty;
	this.capacity = capacity;
	this.suppiler = suppiler;
	this.quantity = quantity;	
	this.Price = Price;	
	this.image = image;
	this.img = img;	
	}
	 public Product() {
	    }
	public Suppiler getSuppiler() {
		return suppiler;
	}

	public void setSuppiler(Suppiler suppiler) {
		this.suppiler = suppiler;
	}

	public String getPrimarymaterial() {
		return primarymaterial;
	}

	public void setPrimarymaterial(String primarymaterial) {
		this.primarymaterial = primarymaterial;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getWarranty() {
		return warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	public String getCapacity() {
		return capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public MultipartFile getImg() {
		return img;
	}

	public void setImg(MultipartFile img) {
		this.img = img;
	}

	@JsonIgnore
	transient private MultipartFile img;

	public int getId() {
		return Id;
	}

	public void setId(int Id) {
		this.Id = Id;
	}

	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	public double getPrice() {
		return Price;
	}

	public void setPrice(double Price) {
		this.Price = Price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}

ShoppinngCart/src/main/java/com/niit/shoppingcart/model/Suppiler.java
package com.niit.shoppingcart.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.springframework.stereotype.Component;

@Entity
@Table
@Component
public class Suppiler {

	@javax.persistence.Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Id")
	private int id;
	@NotNull
	private int supid;
	@NotNull
	private String supname;
	@NotNull
	private String suplocation;
	@NotNull
	private int categoryid;
	@NotNull
	private int productid;
	@NotNull
	private String productname;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getSuplocation() {
		return suplocation;
	}
	public void setSuplocation(String suplocation) {
		this.suplocation = suplocation;
	}
	public int getSupid() {
		return supid;
	}
	public void setSupid(int supid) {
		this.supid = supid;
	}
	public String getSupname() {
		return supname;
	}
	public void setSupname(String supname) {
		this.supname = supname;
	}
	public int getCategoryid() {
		return categoryid;
	}
	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}
	public int getProductid() {
		return productid;
	}
	public void setProductid(int productid) {
		this.productid = productid;
	}
	public String getProductname() {
		return productname;
	}
	public void setProductname(String productname) {
		this.productname = productname;
	}
	
	
}

ShoppinngCart/src/main/java/com/niit/shoppingcart/controller/HomeController.java
package com.niit.shoppingcart.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import com.niit.shoppingcart.dao.SuppilerDAO;


@Controller
public class HomeController 
{

	
	
	
	
	
	
	@RequestMapping("/")
	
 public String homePage()
 {
		
	 return "home";
 }
//
//	@RequestMapping("/login")
//	public ModelAndView showLoginPage()
//	{
//		ModelAndView mv=new ModelAndView("login");
//		mv.addObject("msg", "you clicked on login");
//		mv.addObject("showloginpage", "true");
//		return mv;
//		
//      }
//	
//	@RequestMapping("/register")
//public ModelAndView  showRegistrationPage()
//{
//	ModelAndView mv=new ModelAndView("registration");
//	mv.addObject("msg", "you clicked registration");
//	mv.addObject("showregistrationpage","true");
//	return mv;
//}
	@RequestMapping("/contactus")
	public ModelAndView  showcontactusPage()
	{
		ModelAndView mv=new ModelAndView("contactus");
		mv.addObject("msg", "you can fill the form");
		mv.addObject("showcontactuspage","true");
		return mv;
	}
	@RequestMapping("/home")
	public ModelAndView  showhomePage()
	{
		ModelAndView mv=new ModelAndView("home");
		return mv;
	}
	

}

ShoppinngCart/src/main/java/com/niit/shoppingcart/controller/SuppilerController.java
package com.niit.shoppingcart.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.google.gson.Gson;
import com.niit.shoppingcart.dao.SuppilerDAO;
import com.niit.shoppingcart.model.Suppiler;

@Controller
public class SuppilerController {

	@Autowired
	SuppilerDAO sd;

	@ModelAttribute("Suppiler")
	public Suppiler createSupplier() {
		return new Suppiler();
	}

	
	
	@RequestMapping("/addSuppiler")
	public ModelAndView display3() {

		ModelAndView mv3 = new ModelAndView("addSuppiler");
		return mv3;
	}
	@RequestMapping("viewsuppilers")
	public ModelAndView display8() {
		ModelAndView m4 = new ModelAndView("viewsuppilers");
		return m4;
	}
	@RequestMapping("viewsuppiler")
	public ModelAndView display9() {
		ModelAndView m4 = new ModelAndView("viewsuppiler");
		return m4;
	}
	@RequestMapping("editsuppiler")
	public ModelAndView display15() {
		ModelAndView m6 = new ModelAndView("editsuppiler");
		return m6;

	}	
	@RequestMapping(value = "listsup", method = RequestMethod.GET, produces = "application/json")
	public @ResponseBody String showList()
	{
		List list = sd.getAllSuppilers();
		Gson x = new Gson();
		String json = x.toJson(list);
		return json;
	}

	 @RequestMapping(value="editsuppiler",method=RequestMethod.GET)
	    public ModelAndView editSup(@RequestParam int id){
		 Suppiler supplier1=sd.getSingleSuppiler(id);
	    	return new ModelAndView("editsuppiler","Supplier",supplier1);
	    }

	@RequestMapping(value="storesuppiler",method=RequestMethod.POST)
	public String addSuppiler(HttpServletRequest request,@Valid @ModelAttribute("Suppiler")Suppiler suppiler,BindingResult result)
	{
		System.out.println(result.hasErrors());
		if(result.hasErrors())
		{
			return "addSuppiler";
			
		}
		sd.saveOrUpdate(suppiler);
		return "redirect:/viewsuppilers";
	}
	@RequestMapping(value = "viewsuppiler", method = RequestMethod.GET)
	public ModelAndView viewSup(@RequestParam int id, @ModelAttribute Suppiler suppliers) {
		Suppiler supplier = sd.getSingleSuppiler(id);
		return new ModelAndView("viewsuppiler", "Supplier", supplier);
	}
	 @RequestMapping(value="updatesuppiler",method=RequestMethod.POST)
	    public String updateSupplier(HttpServletRequest request,@Valid @ModelAttribute("Suppiler")Suppiler editsup,BindingResult result,Model model)
	    {
			sd.update(editsup);
			return "redirect:/viewsuppilers";
	    }	 
		
	 @RequestMapping("/deletesuppiler")
		public String deleteSupplier(@RequestParam int id) {
			sd.delete(id);
			return "redirect:/viewsuppilers";
		}

	}

ShoppinngCart/src/main/webapp/WEB-INF/views/Coroseul.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<style>

  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
      margin: auto;
  }
  </style>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>
<body>

<div class="container">
		<br>
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
				<li data-target="#myCarousel" data-slide-to="3"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img src="<c:url value="/resources/images/image1.jpg"/>" alt="HarlyDavid" width="300" height="150">
				</div>

				<div class="item">
					<img src="<c:url value="/resources/images/image2.jpg"/>" alt="Harly"
						width="300" height="150">
				</div>

				<div class="item">
					<img src="<c:url value="/resources/images/image3.jpg"/>" alt="Yamaha R15"
						width="300" height="150">
				</div>

				<div class="item">
					<img src="<c:url value="/resources/images/image4.jpg"/>" alt="Honda Cbr500"
						width="300" height="150">
				</div>
				<div class="item">
					<img src="<c:url value="/resources/images/image5.jpg"/>" alt="Suzuki"
						width="300" height="150">
				</div>
				<div class="item">
					<img src="<c:url value="/resources/images/image6.jpg"/>" alt="Ktm"
						width="300" height="150">
				</div>
			</div>


			<!-- Left and right controls -->
			<a class="left carousel-control" href="#myCarousel" role="button"
				data-slide="prev"> <span
				class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a> <a class="right carousel-control" href="#myCarousel" role="button"
				data-slide="next"> <span
				class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
			
		</div>
	</div>
</body>
</html>

ShoppinngCart/src/main/webapp/WEB-INF/views/Nav.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<html>
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
ul { list-style-type:none; margin:1; padding:1; padding-top:7px; padding-bottom:5px; }

body{
     
    background:url('https://www.clipartsgram.com/image/1127858435-background-images-for-websites-24.jpg');
    background-repeat: no-repeat;
    -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
    padding:80px;
}


#login-dp{
    min-width: 150px;
    padding: 14px 14px 0;
    overflow:hidden;
    background-color:rgba(255,255,255,.8);
}
#login-dp .help-block{
    font-size:12px    
}
#login-dp .bottom{
    background-color:rgba(255,255,255,.8);
    border-top:1px solid #ddd;
    clear:both;
    padding:14px;
}
#login-dp .social-buttons{
    margin:12px 0    
}
#login-dp .social-buttons a{
    width: 49%;
}
#login-dp .form-group {
    margin-bottom: 10px;
}
.btn-fb{
    color: #fff;
    background-color:#3b5998;
}
.btn-fb:hover{
    color: #fff;
    background-color:#496ebc 
}
.btn-tw{
    color: #fff;
    background-color:#55acee;
}
.btn-tw:hover{
    color: #fff;
    background-color:#59b5fa;
}
@media(max-width:768px){
    #login-dp{
        background-color: inherit;
        color: #fff;
    }
    #login-dp .bottom{
        background-color: inherit;
        border-top:0 none;
    }
}
.navbar navbar-default navbar-inverse{
position:top;
}

</style>
</head>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<body>

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="home">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">  
     <li><a href="register"><span class="glyphicon glyphicon-log-out"></span>SignUp</a></li>
      <li><a href="login"><span class="glyphicon glyphicon-log-out"></span> Login</a></li>
    </ul>
  </div>
</nav>


</body>
</html>

ShoppinngCart/src/main/webapp/WEB-INF/views/addSuppiler.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet"
	href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script
	src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="home">Home</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="viewProducts">Manage Products</a></li>
      <li><a href="viewSuppilers">Manage Suppilers</a></li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>
<h2>Add a Suppiler</h2>
    <div class="container" ng-app="imgApp" ng-controller="imgCtrl">
    <c:url var="addsupplier" value="addSuppiler"></c:url>
   <form:form commandName="Suppiler" method="post" action="storesuppiler">
       <table class="table table-bordered" >
           <tr><td><form:label path="supid">Suppiler Id:</form:label></td>
               <td><form:input path="supid"/>
               <font color="red"><form:errors path="supid"></form:errors></font></td>
           </tr>
           <tr><td><form:label path="supname">Suppiler Name :</form:label></td>
               <td><form:input path="supname"/>
               <font color="red"><form:errors path="supname"></form:errors></font></td>
           </tr>           
           <tr><td><form:label path="suplocation">Suppiler Location:</form:label></td>
               <td><form:input path="suplocation"/>
               <font color="red"><form:errors path="suplocation"></form:errors></font></td>
           </tr>
           <tr><td><form:label path="categoryid">Category Id :</form:label></td>
               <td><form:input path="categoryid"/>
               <font color="red"><form:errors path="categoryid"></form:errors></font></td>
           </tr>           
           <tr><td><form:label path="productid">Product Id :</form:label></td>
               <td><form:input path="productid"/>
               <font color="red"><form:errors path="productid"></form:errors></font></td>
           </tr>           
           <tr><td><form:label path="productname">Product Name :</form:label></td>
               <td><form:input path="productname"/>
               <font color="red"><form:errors path="productname"></form:errors></font></td>
           </tr>
             <td><input type="submit" value="addSuppiler" class="btn-success"/></td>
       </table>
   </form:form> 
   </div>
   	<footer class="container-fluid text-center">
		<p>©Bibliopole-All Rights Reserved</p>
		<P>2016</P>
	</footer>
   
</body>
</html>

ShoppinngCart/src/main/webapp/WEB-INF/views/editproduct.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta charset="utf-8">
<meta Name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
	href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script
	src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="Admin">Admin Home</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="ManageProducts">Manage Products</a></li>
      <li><a href="ManageSupplier">Manage Suppilers</a></li>
      <li><a href="ManageUsers">Manage Users</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="Logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>
<h2>Edit Product</h2>
  <form:form  modelAttribute="Product" method="post" action="updateproduct" enctype="multipart/form-data">
   <table class="table table-bordered" >
      <tr><td><form:label path="Name">Product Name :</form:label></td>
               <td><form:input path="Name" value="${product.name}"/></td>
           </tr>
               <tr><td><form:label path="Price">Product Price :</form:label></td>
               <td><form:input path="Price" value="${product.price}"/></td>
           </tr>
           <tr><td><form:label path="Description">Description :</form:label></td>
               <td><form:input path="Description" value="${product.description}"/></td>
           </tr>
                <tr><td><form:label path="primarymaterial">Primary Material :</form:label></td>
               <td><form:input path="primarymaterial" value="${product.primarymaterial}"/></td>
           </tr>
              <tr><td><form:label path="style">Style :</form:label></td>
               <td><form:input path="style" value="${product.style}"/></td>
           </tr>
          
              <tr><td><form:label path="warranty">Warranty :</form:label></td>
               <td><form:input path="warranty" value="${product.warranty}"/></td>
           </tr>
              <tr><td><form:label path="capacity">Capacity :</form:label></td>
               <td><form:input path="capacity" value="${product.capacity}"/></td>
           </tr>
           <tr><td><form:label path="img">Product Image :</form:label></td>
               <td><form:input path="img" type="file" />
               <font color="red"><form:errors path="img"></form:errors></font></td><tr>
               <tr><td></td>
               <td><input type="submit" value="submit" class="btn-success"/></td>
           </tr>
           </table>
                      
  </form:form>   
  	<footer class="container-fluid text-center">
		<p>©Bibliopole-All Rights Reserved</p>
		<P>2016</P>
	</footer>
  
</body>
</html>

ShoppinngCart/src/main/webapp/WEB-INF/views/footer.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

</head>
<body>
  <div class="navbar navbar-default navbar-fixed-bottom" style="text-align:center;background-color:black;">
  
    <div class="container">
      <p style="text-align:center;color:white;">
     <br>@2017@ - ALL RIGHTS RESERVED.
          </p>
      
      </div>
    
    
  </div>

</body>
</html>

ShoppinngCart/src/main/webapp/WEB-INF/views/viewproduct.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib prefix="x" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<html>
<head>
     <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
	href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script
	src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<title>Product Details</title>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="home">Home</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
    
    <li><a href="#" style ="color:white;">Welcome.... <%=session.getAttribute("loggedInUser") %></a></li>
      
      <li><a href="${pageContext.request.contextPath}/home"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>

</head>
<h2>Product Details</h2>
 
      
            <table class="table table-hover table-bordered">
            <tr><td rowspan="5">
            <img src='<x:url value="resources/images/${product.image}"/>'/></td></tr>
            
            <tr><td><b>${product.id}</b></td></tr>
            <tr><td><b>${product.name}</b></td></tr>
            <tr><td><b>${product.price}</b></td></tr>
            <tr><td><b>${product.description}</b></td></tr>
            </table>
            <sec:authorize access ="hasRole('ROLE_USER')">
      <a href="viewCart?id=${product.id}" class="btn btn-info">Add cart</a>
    </sec:authorize>
      	<footer class="container-fluid text-center">
		<p><b>All Rights Reserved</b></p>
		<P>2016</P>
	</footer>
      
   </body>
</html>